---
- name: Service start nginx
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true

- name: Reload nginx
  become: true
  ansible.builtin.command: nginx -s reload
